services:
  iaya-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_DIRECTUS_URL=https://cms.iaya.cloud
        - VITE_DIRECTUS_TOKEN=MkFqoSUe6Xxxb8nPumDjPiKBTxRLvZqT
    container_name: iaya-prod
    restart: unless-stopped
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iaya-prod.rule=Host(`iaya.cloud`) || Host(`www.iaya.cloud`)"
      - "traefik.http.routers.iaya-prod.entrypoints=websecure"
      - "traefik.http.routers.iaya-prod.tls.certresolver=mytlschallenge"
      - "traefik.http.services.iaya-prod.loadbalancer.server.port=80"

networks:
  root_default:
    external: true
