services:
  iaya-staging:
    build:
      context: .
      args:
        - VITE_DIRECTUS_URL=${VITE_DIRECTUS_URL}
        - VITE_DIRECTUS_TOKEN=${VITE_DIRECTUS_TOKEN}
    container_name: iaya-staging
    ports:
      - "5173:80"
    restart: always
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iaya-staging.rule=Host(`staging.iaya.cloud`)"
      - "traefik.http.routers.iaya-staging.entrypoints=web,websecure"
      - "traefik.http.routers.iaya-staging.tls=true"
      - "traefik.http.routers.iaya-staging.tls.certresolver=mytlschallenge"
      - "traefik.http.services.iaya-staging.loadbalancer.server.port=80"

networks:
  root_default:
    external: true
