services:
  iaya-staging:
    build:
      context: .
      args:
        - VITE_DIRECTUS_URL=${VITE_DIRECTUS_URL}
        - VITE_DIRECTUS_TOKEN=${VITE_DIRECTUS_TOKEN}
    container_name: iaya-staging
    ports:
      - "5173:80"
    restart: always
