services:
  iaya-staging:
    build: .
    container_name: iaya-staging
    ports:
      - "5173:80"
    restart: always
    environment:
      - VITE_DIRECTUS_URL=${VITE_DIRECTUS_URL}
      - VITE_DIRECTUS_TOKEN=${VITE_DIRECTUS_TOKEN}
